### ISSUE TITLE
Please add IP address to "Start Host Server" on main hamburger menu

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#102]
We love having "Connect as Client" and "Start Host Server" available right on the main hamburger menu, without having to drill through "Settings."

Can we request a new feature? Can the "Start Host Server" entry display the IP address, just as the "Connect as Client" entry does? This change would resolve a difficulty we had the other day, where we couldn't get our client to connect.  We hadn't realized that for some reason the host IP address had changed (both are mobile devices).

Thanks!

**Comment by kehood** [comment]
Just created a PR for this.

https://github.com/Tarmslitaren/FrosthavenAssistant/pull/103

**Comment by Tarmslitaren** [comment]
MR is merged and in version 1.8.0. Thanks for contributing!
