### ISSUE TITLE
X-haven on MacBook (OSX)

### ISSUE THREAD

**Issue by macrom** [Tarmslitaren/FrosthavenAssistant#104]
What can I do? We use my MacBook as the server. I could use previous versions for Gloomhaven, but apparently I am not able to download the last version for Frosthaven? Now it seems that "X-haven Assistant is only available on IOS.". Argh! Help/Insight please.

![image](https://user-images.githubusercontent.com/8341154/220834402-4d0a365e-5a7b-4fb6-a963-b4f6109676f1.png)

**Comment by Tarmslitaren** [comment]
you can download mac version from releases tab here on GitHub.

I understand that you can also use the ios version in case you you have an
m2 chipset mac.

**Comment by kehood** [comment]
I use it on my macbook pro m1 currently.  It downloaded form the app store even though it says "optimized for ipad" it still works.

**Comment by macrom** [comment]
I was able to get the latest OSX release downloaded and it runs just fine on my 2012 MacBook. The Assets list wouldn't load previously, but was populating the list tonight. Thanks for the assistance.

**Comment by TylerHelmuth** [comment]
I am able to run the Releases page version perfectly on my M1.

**Comment by Tarmslitaren** [comment]
I will close this ticket since it's solved
