### ISSUE TITLE
FH Scenario 10 missing item

### ISSUE THREAD

**Issue by kjc17710** [Tarmslitaren/FrosthavenAssistant#105]
Hello,

Amazing work and thank you for everything you are doing. As we were playing scenario 10 in Frosthaven, it was missing the ice pillars that get added after you read section 65.3. A lot of the other scenarios had a button in the bottom to add these specific enemies/objectives and this one didn't have one.

Thank you!

**Comment by Tarmslitaren** [comment]
Thanks for the report. Will add the section for next version

**Comment by Tarmslitaren** [comment]
fixed on 1.8.0
