### ISSUE TITLE
FH enhancement request

### ISSUE THREAD

**Issue by kjc17710** [Tarmslitaren/FrosthavenAssistant#106]
Hello! 

This is more of a quality of life improvement rather than an issue. It would be nice to be able to switch from normal to elite or vice versa when adding monsters. Most of the time when setting up a scenario we have to add many different enemies, both normal and elite. We have been doing it with the specific plus buttons for each side, it would be nice if there was a way to switch to the other one within the same modal window rather than having to close out and pick the other side (esp. since sometimes it will move the monster around in the initiative order).

Thank you!

**Comment by Tarmslitaren** [comment]
this is how auto add standees are setup now (1.8.0). since that is likely the majority of your added standees I will close this ticket
