### ISSUE TITLE
Bug - Adding a summoned monster of a new type draws a monster ability card

### ISSUE THREAD

**Issue by sirrus233** [Tarmslitaren/FrosthavenAssistant#117]
When a monster is summoned, and that monster is the first of its type to be added to the tracker, the app will automatically draw an ability card for that monster type (just like it would when a room of new enemies is revealed). This is incorrect behavior, since a summoned monster does not use an ability on the turn it is summoned.

**Comment by Tarmslitaren** [comment]
I'm not entirely sure of this, since you might need to draw a card to determine turn order for focus reasons ( i.e you have a summon that will determine its target based on initiative). Have to consult FAQs or rulebook...

**Comment by sirrus233** [comment]
I just checked the rulebook (pg. 43) and you are quite right! My apologies. The ability card IS drawn, for the purpose of determining initiative. TIL!

Closing.
