### ISSUE TITLE
Suggestion: show only calculated stats on the card for enemy ranks present

### ISSUE THREAD

**Issue by retupmoc258** [Tarmslitaren/FrosthavenAssistant#119]
For example, if you only have normal hounds, it would be great to only see the normal attack values instead of normal and elites. Or vice versa.

This especially became an issue in Scenario 65 for our group, where one enemy has ranged if normal and no range if elite. We didn't understand the range reference being "normal". We thought that meant without any other modifier. It wasn't until afterward that we understood. Since there was only 1 elite of this monster type, it would have saved some confusion if only the elite calculation was present.

**Comment by Tarmslitaren** [comment]
this is not a calculation, but a feature of that specific monster. I'd prefer the calculations only to add the numbers, not remove things written on the physical cards.
