### ISSUE TITLE
Apps not syncing 

### ISSUE THREAD

**Issue by Coffee4cr** [Tarmslitaren/FrosthavenAssistant#120]
The android app 1.8 doesn't seem to want to sync unless we connect /disconnect

We see the update on the pc(server) from one device

But the other devices aren't seeing it

**Comment by objayfred** [comment]
Yes, we had a similar experience last night after yesterday's update.  All on the same local network between a PC, three android phones, and an android tablet.  Used the PC to host to start as has worked well for the previous version, then switching to using one of our phones to host to see if that improved things, had constant desyncing, both with error messages and without.  Also don't think we ever saw deck animations appear on other devices, even when synched.

**Comment by Tarmslitaren** [comment]
there. was some refactoring done on the server/client it looks like it broke a couple of things. need to get to the bottom of it.
