### ISSUE TITLE
Apex Demon missing from Crimson Scales scenario #16

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#13]
WE recently played Crimson Scales #16: Preto Krisanta.  It’s missing an enemy.  The enemy is the Apex Demon.  It’s an elite earth demon with normal hit points multiplied by C+1, has +2 to all move abilities, and has a bunch of immunities.

Incidentally, in the preceding scenario (#15), we were very impressed at all the help you provided about what enemy to spawn when.  Much appreciated!

**Comment by Tarmslitaren** [comment]
The Apex Demon is added by adding the section. Alternatively it can be added manually through add monster menu (tick show special monsters)
