### ISSUE TITLE
Coral solo scenario incorrect monster prompt

### ISSUE THREAD

**Issue by christyray** [Tarmslitaren/FrosthavenAssistant#130]
I'm absolutely loving the new update to auto-prompt for spawned monsters! Seriously one of the biggest quality-of-life changes I didn't know I needed but now I never want to play without. 

Just wanted to report a small bug - the Coral solo scenario prompts for 4 normal Lightning Eels at the start of the 3rd round, but it should be 4 elite Lightning Eels. 

Thanks again for the great app!

**Comment by Tarmslitaren** [comment]
thanks! will be fixed in next verison.

**Comment by Tarmslitaren** [comment]
fixed in 1.8.2
