### ISSUE TITLE
Missing Ally Modifier Deck

### ISSUE THREAD

**Issue by chrisstyves** [Tarmslitaren/FrosthavenAssistant#131]
In 1.8.1 the Ally Modifier Deck is sometimes missing.

To reproduce:

1. Open Frosthaven Scenario 112 (a scenario with allies)
2. Enter initial standee #s in the dialog that pops up
3. Note that the ally deck is not visible

Note that the deck appears normally for this scenario in 1.7.2 after adding the starting standees.

**Comment by Tarmslitaren** [comment]
It seem to work normally, but is not showing if you have "Hide loot deck" setting on and there are section buttons visible and scaling is such that the regular monster attack modifier deck is on the bottom bar. Will find a fix. Thanks for reporting.

**Comment by Tarmslitaren** [comment]
fixed in 1.8.2
