### ISSUE TITLE
Scenario 10 wrong hp calculation for ice pillars in 2nd room

### ISSUE THREAD

**Issue by darkii1** [Tarmslitaren/FrosthavenAssistant#133]
Ice pillars in second room use different (from first room) formula, can be found in 65.3. It also would be nice to have ice pillars count in second room depending on character count. Thank you

**Comment by Tarmslitaren** [comment]
thanks! will be fixed in next version

**Comment by Tarmslitaren** [comment]
fixed on 1.8.2
