### ISSUE TITLE
Scenario #96 - none of the section buttons add anything.

### ISSUE THREAD

**Issue by PeteWaite** [Tarmslitaren/FrosthavenAssistant#137]
That's it really.

**Comment by Tarmslitaren** [comment]
thanks. fixed for next version.

**Comment by Tarmslitaren** [comment]
I don't see anything like that for Frosthaven scenario 96? did you mean another one?

for 97 I think you need to do it old school, though you can reveal and discard cards through the ability cards menu ( tap monster ability card to open )

Also the 'Tall drunken tale' scenario might be hard o
to do some things with the app.

**Comment by PeteWaite** [comment]
Sorry, yes, 97.
Still working through it.
Thanks

**Comment by PeteWaite** [comment]
Hiya,
Sorry again.

So we just completed it.
Not that impressed.

We played at reduced difficulty but that didn't make much difference.

The pressure plates and the whole take monster cards into your hand thing
was completely irrelevant.

The boss just kept teleporting next to us and we just slowly killed him.

As for the monster deck functionality, only one of us stepped on a pressure
plate and took two monster cards but never played them.

Almost a waste of time.

I don't think we did anything wrong.

For the app, maybe for this scenario you could disable the monster decks?

Thanks anyway.
Pete

**Comment by Tarmslitaren** [comment]
sections missing spawns fixed in 1.8.2. 

I will add a note for the user to use physical decks for this scenario for the next version.

**Comment by Tarmslitaren** [comment]
fixed in 1.8.3
