### ISSUE TITLE
Crimson Scales scenario 25 issue with Brightspark Mercenary

### ISSUE THREAD

**Issue by SwedishEagle** [Tarmslitaren/FrosthavenAssistant#138]
If you start Crimson Scales scenario 25: Brightspark Behold with a mercenary Brightspark in your party your mercenary becomes a second copy of the scenario NPC Brightspark. This is also permanent so even switching to a new scenario your mercenary will still be a NPC Brightspark :D.
I had to remove him from party and readd a new Brightspark to fix the issue.

**Comment by Tarmslitaren** [comment]
thanks! Fixed for next version.

**Comment by Tarmslitaren** [comment]
I wouldn't expect brightspark character to normally be available for that scenario though. It's a bit meta ;)

**Comment by Tarmslitaren** [comment]
fixed in 1.8.2
