### ISSUE TITLE
Continual difficulties connecting client to server

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#14]
We have not been able to connect client to server reliably—to the point where we have more or less given up, which is a pity.

The error we encounter most commonly is failure to connect when tapping the checkbox for connection.  The error message mentions a port that is _not_ the one we should be trying to connect to:
![52A7FFA8-43D6-42D1-B4E7-3BB339C8D824](https://user-images.githubusercontent.com/37659/199367704-5b340978-7273-41a6-96d7-15bb6c37518b.png)

When we have been able to get the connection to work, the message shows port 4567 as expected.

![0F01F9D0-A62C-4A9F-80CB-33C1129FFB18](https://user-images.githubusercontent.com/37659/199367763-1a038e64-013d-4ec1-8af2-841c08d3d070.jpeg)

I believe we have version 1.3.1 on both platforms.  The server is running Android 8 and the client is Android 12 or 13.  (I can’t remember whether I last tried before or after the upgrade from 12 to 13.)

If there is some diagnostic process I can go through that will provide more information, or if there is a log file somewhere in internal storage, please do let me know.

**Comment by Tarmslitaren** [comment]
sorry, I don't have too much logging. 

potential problems:
1. make sure all devices are on the same wifi.
2. after switching to wifi, wait a few seconds (or leave the settings menu and come back) before trying to start server / connect as client
3. If one of the devices is hosting a wifi hotspot, that device can not be connected to.

The port in the error message, is as far as I can tell not really relevant.

You could try another port see if that helps.

These are 2 real devices right, no emulation?

I haven't been able to reproduce this particular error

**Comment by nrnrnr** [comment]
Yes, same wifi.  These are two real devices (Nvidia Shield K1 tablet and Google Pixel 6 phone).  As mobile devices they are always on wifi.  As far as I know they are not hosting any hotspots, but I will investigate.

I have tried other ports; same result.

What sort of information might be helpful in a bug report?

**Comment by Tarmslitaren** [comment]
Can you check if your both devices are not blocking any of the apps permissions ( internet, location )

**Comment by Tarmslitaren** [comment]
Just a thought. It's hard without being able to repro myself. Did find an article describing problem with nvidia shield sometimes dropping wifi, but I wouldn't put too much stock on it. 

If you have access to other devices, could you see if the problem is consistently there? shouldn't ( probably maybe) matter if it's android, iDevice or pc.

**Comment by nrnrnr** [comment]
You nailed it.  The Nvidia Shield Tablet K1 seems to drop Wifi periodically.  Wifi goes out and then returns within 1 to 3 seconds.  It's a pity since of all the devices that one has by far the best form factor for using on the table.   We will try using a phone as the server and make the tablet a client.  And if the tablet loses its wifi it probably will not be hard to reconnect.
