### ISSUE TITLE
Increasing max HP in-round does not update immediately

### ISSUE THREAD

**Issue by PeteWaite** [Tarmslitaren/FrosthavenAssistant#140]
We have the Travelling Cloak which increases our max HP at the start of the scenario, but if we forget to apply it's effect and start the scenario, we find that we can go and change the max HP in the character's level dialog, but sometimes the character's panel on the main screen doesn't always update unless we force a redraw of the screen by doing something else (like marking a figure's turn done).
Not sure, don't know the mechanism, but it could be that increasing max HP for a character that has already had its turn might be a case where the value on the main screen does not update.

**Comment by rathe** [comment]
I find that updating a party member's name from a client does not always (ever?) update the server. I have not tested to see if updating on the server updates clients, nor if this happens 100% of the time. This seems to be an issue introduced with 1.8.0, but I may be misremembering from prior versions (I've only been using XHA for 1-2 months).

I was about to file this as a bug, but I wonder if the two are related.

**Comment by Tarmslitaren** [comment]
seems like max health does not update in case the character's current health is not max.

 The name not updating to server is not related: since change name is only cosmetic, I didn't make it a 'game changing command' and so it does not update immediately on the server. It should update when you do something else that changes the game state.

**Comment by Farthom** [comment]
I can confirm increasing the Max HP does correctly update the server now. However the related issue reported by @rathe about changing the player name is NOT fixed in 1.8.2

**Comment by rathe** [comment]
Can confirm that Names are in the same state as previous. It is fine that changing name doesn't trigger a feed, however what I find is that if I change the name on my client, but another client updates first, my name reverts back. If I am the first to make a game-state change, the name feeds over.

I will file this last finding as a separate issue, as @Tarmslitaren has confirmed this is separate from HP behaviour.
