### ISSUE TITLE
Feature Request: Parties

### ISSUE THREAD

**Issue by rathe** [Tarmslitaren/FrosthavenAssistant#141]
For the purpose of using the same X-Haven Assistant server and/or clients in multiple campaigns, allow the saving of party composition in a group, and allow the saving of, and selection from, multiple groups.

**Minimum group elements:**
1. Party Name (e.g., "Thursday Gloomhaven", "The Murderhobos", "Brandon's Sunday Funday Campaign", "Caitlin's Really Cool Party", "Guardians of the Gaylápagos")
2. Party composition

**Minimum party member elements:**
1. Name (e.g., "Voidwarden", "Princess Sparkletime von Poopypants", "Hamtarino", "Ix", "Trogdor the Burninator")
2. Class
3. Level

**Considerations:**
1. Should the group be saved to client, server, or both?
2. Should connecting to a server overwrite the client's party list with the server's list?
3. Should connecting to a server add the server's party list to the client's list? Add the client's list to the server's?

**Possible Additional Functionality:**
1. "Default Campaign" group element: setting this automatically changes which "Current Campaign" is selected in the Set Scenario menu when the party is loaded
2. "Player Name" party member element: I dunno, maybe someone's got a lot of campaigns and has trouble remembering who plays what, or who's in which group? People meet infrequently sometimes.
3. "Active" checkbox party member element: When checked (default), party member is automatically added when Set Scenario is performed. This facilitates switching players out in the same campaign. (Credit @sigismond0, #73)
4. Save mid-scenario party member attributes, such as Current HP, Current XP, Applied Statuses, etc, to facilitate party switching when a long-running scenario is split across sessions that bridge sessions from other campaigns

**Additional Functionality considerations:**
1. Should changing the Current Campaign in Set Scenario also change the group's Default Campaign?

**Comment by rathe** [comment]
#73 also requests related functionality. I'll add "Active/Inactive" under Additional Functionality in the original.

**Comment by Tarmslitaren** [comment]
Simplest would probably be to introduce saves for the entire state. Since beyond characters there are persistent changes to loot deck in Frosthaven that you'd want to preserve as well.

**Comment by Tarmslitaren** [comment]
Added manual saves in version 1.9.0. This will hopefully be enough, so I will close this issue
