### ISSUE TITLE
Feature Request - push notifications

### ISSUE THREAD

**Issue by jhedin** [Tarmslitaren/FrosthavenAssistant#142]
When a new round starts and everyone needs to add numbers for initiative, send a push notification

Ideally, this would come with config for setting ownership over one or many characters, so I can also be notified when it's my turn to go, or if everyone's waiting for my initiative.

**Comment by rathe** [comment]
This is a highly complex ask, but would be VERY nice to have.

**Comment by Tarmslitaren** [comment]
You should know which characters have their initiative set by the ?? right? Applying ownership over characters would introduce a lot of complexity for very little gain. You'd typically know which character is yours after all.

**Comment by Tarmslitaren** [comment]
Closing as won't fix. the complexity outweighs the benefits
