### ISSUE TITLE
Feature: Docker functionality preparations

### ISSUE THREAD

**Issue by Bockiii** [Tarmslitaren/FrosthavenAssistant#147]
Hi,

I wanted to create a docker image for x-haven but ran into a few missing features that would be required for it to work "easily" without doing too many hacks :)

Things that would be needed:
- Starting the app as a "server only" without gui
- Ability to define a settings file during startup (to be able to run multiple sessions in parallel)

I could then provide you the dockerfile and github action to build it on every release.

**Comment by Bockiii** [comment]
I forgot to add: This functionality would be only needed for the linux version, although it might be interesting for the other OSes as well.

**Comment by desidius** [comment]
I hope this can be implemented with an additional config for the client itself, even using the current "state" json file for additional settings.
Just something simple like "startServer": True, "port":4567 would be really useful.

I'd love a server only release that does not require wireless support for windows (don't know if that is required for linux) and that can be run headless but the config file would be a life changer.

**Comment by aschneem** [comment]
I have a pull request for a refactor that addresses this issue. It ended up be more complex than hoped, but I'd appreciate additional testing if anyone on this thread is able.
PR: https://github.com/Tarmslitaren/FrosthavenAssistant/pull/229
Docker Hub: https://hub.docker.com/r/aschneem/x-haven-server
