### ISSUE TITLE
Name change update reverted if another client updates first

### ISSUE THREAD

**Issue by rathe** [Tarmslitaren/FrosthavenAssistant#148]
**Condition**
Change name on app, "Client 1"

**Expected Behaviour**
Name is changed on server, "Server", and other connected clients, "Client 2" immediately.

**Actual Behaviour**
If Client 1 makes the next update, the name change populates to Server and Client 2 as expected. However, if Client 2 or Server makes an update before Client 1, the name on Client 1 is reverted to what is set on the app that performed the update.

It should be noted that the fact of Name change not being a game-changing command, as stated by @Tarmslitaren in #140, may lead inexperienced users to believe the functionality is bugged. I agree that it is cosmetic and doesn't really _need_ to be reflected to everyone, but it may create a perception. Every other change I've made has triggered an update (including level change which, per RAW, will never be done mid-scenario), so this feels like a singled-out difference, which originally led me to believe it was a bug.

**Comment by Tarmslitaren** [comment]
fixed in 1.8.3
