### ISSUE TITLE
FH Scenario 101 reminder request

### ISSUE THREAD

**Issue by kjc17710** [Tarmslitaren/FrosthavenAssistant#151]
Hello,

During the scenario the poison traps are supposed to move towards Zu, and Zu towards the poison traps. It would be nice at the end of each round/start of each new round a reminder would pop up to move these items closer to each other.

This applies after reading section 126.2.

Thank you for your work!

**Comment by Tarmslitaren** [comment]
will be fixed in next version

**Comment by Tarmslitaren** [comment]
added in 1.8.3
