### ISSUE TITLE
FH Enhancement request - challenges

### ISSUE THREAD

**Issue by kjc17710** [Tarmslitaren/FrosthavenAssistant#152]
Hello,

Playing through the game with the challenges deck, it would be nice if there was a way to accommodate a few of them.

Alternate Tactics - during ordering of the initiative each round, initiative is ordered from highest to lowest
Increasing Aggression - whenever a (-1) or (-2) attack modifier card is drawn from the monster attack modifier deck, after the attack, remove the card from the deck for the remainder of the scenario (you can remove negative cards from the deck, but it seemed to reset the deck when you clicked it)

Thank you for everything!

**Comment by Tarmslitaren** [comment]
added in 1.8.4: from amd deck menu, you may tap a card in discard column, to remove it.
