### ISSUE TITLE
FH Enhancement request - selectable background color (Spoiler for meteor, snowflake and shackles colors)

### ISSUE THREAD

**Issue by kjc17710** [Tarmslitaren/FrosthavenAssistant#153]
Hello,

We were playing with three characters, Meteor, snowflake and shackles, which all had a similar dark grey background. It became a little confusing whose turn it was and slowed down inputting initiative. It would be nice if there was an option to change the background color of the character bars so we can make them more easily recognizable.

![image](https://user-images.githubusercontent.com/58891753/230693985-d46d27ce-9d30-411f-a630-922891ea3687.png)

Thank you!

**Comment by scottmk** [comment]
You should put a spoiler warning in the title of this issue.

**Comment by Tarmslitaren** [comment]
changed the background colors for those classes in version 1.9.0, so I will now close this issue.
