### ISSUE TITLE
Wrong Host Server IP address in 1.8.2 Update

### ISSUE THREAD

**Issue by SovietVVinter** [Tarmslitaren/FrosthavenAssistant#154]
Hi, I read [Issue 139](https://github.com/Tarmslitaren/FrosthavenAssistant/issues/139) and it seemed to have a similar cause but whatever change you made doesn't fix it for me and it looks like it's trying to use a vEthernet IP address from Bluestacks (172.22.0.1) instead of my normal Ethernet IP Address. Is this something I should/need to fix on my end?
![image](https://user-images.githubusercontent.com/71097199/230752502-9be13e8c-5449-449b-b37a-2083762cc75e.png)

**Comment by Tarmslitaren** [comment]
potential fix in 1.8.3. please try it out and comment
