### ISSUE TITLE
Scenario 31 - Night Demons as Allies

### ISSUE THREAD

**Issue by tjacobs143** [Tarmslitaren/FrosthavenAssistant#156]
https://github.com/Tarmslitaren/FrosthavenAssistant/blob/50f89014a6c29ef92130336f72c7220e33997618/frosthaven_assistant/assets/data/editions/Gloomhaven.json#L4414

This section seems to create the Night Demons as allies for Gloomhaven scenario 31 which is not correct from our reading of the scenario rules.

**Comment by Tarmslitaren** [comment]
thanks! will be fixed in next version

**Comment by Tarmslitaren** [comment]
fixed in 1.8.3
