### ISSUE TITLE
Windows Desktop - can't 'Start Host Server' - Failed to get wifi IPv4

### ISSUE THREAD

**Issue by andreacantatore62** [Tarmslitaren/FrosthavenAssistant#16]

**Comment by Dorkpassenger** [comment]
Seeing the same issue, PC is connected to the wifi router via ethernet.  PC can connect to another server hosted on the network.

**Comment by Shamalanana** [comment]
It's a known issue as stated in the Readme. The server/client only works if your "server" has a wifi (local) IP address. Rules out internet play currently. 

Can the whole WiFi check be removed? I like running the "server" on my home server while playing away. I've got my router set to forward and even set up a dynamic hostname for friends/family to get to it. That server does not (and will never) have WiFi capabilities. I'd sooner learn flutter and fix it myself.

**Comment by Shamalanana** [comment]
> There is a fix for next version: if no wifi connection, will default to ipv4 ethernet if that exits. Please be patient for a week or so while I finalize other important fixes.

First off, that's a fantastically fast response. The community thanks you for addressing it. Secondly, your project has still inspired me to learn flutter so a second thank you for that.

**Comment by Tarmslitaren** [comment]
Not all that fast. The issue has been reported before, I just didn't have an Ethernet cable to test with. So it was fixed an hour ago. Your message was just good timing ;)

Have fun with flutter! It's quite easy to get going, but the deeper you go the more issues there are with it.

**Comment by Tarmslitaren** [comment]
fixed in 1.5.5
