### ISSUE TITLE
Spawn correction in FH scenarios 41 and 71 for 3P

### ISSUE THREAD

**Issue by ff2happy** [Tarmslitaren/FrosthavenAssistant#160]
Hi,
Thanks for this fantastic app! It greatly streamlines my solo FH playthrough :)

I noticed the spawns for 3 players are wrong in scenarios 41 and 71.
In scenario 41, elite Living Spirits spawn while they should be normal for 3P.
In scenario 71, section 111.2, on odd rounds, 2 elite Pirhana Pigs spawn while they should be normal.

**Comment by Tarmslitaren** [comment]
thanks! will be fixed in next version

**Comment by Tarmslitaren** [comment]
fixed in 1.8.3

**Comment by ff2happy** [comment]
Thanks!
