### ISSUE TITLE
JotL Scenario 22: incorrect Stone Golem type

### ISSUE THREAD

**Issue by detecfiregreat** [Tarmslitaren/FrosthavenAssistant#166]
The Stone Golem in Scenario 22 is being created in the app as a modified *normal*, not a modified *elite* as listed in the scenario. Small configuration change needed in the metadata for this scenario, 1 *elite* to replace the 1 *normal* for all three player counts.

**Comment by Tarmslitaren** [comment]
fixed in 1.8.4.
