### ISSUE TITLE
GUI accessibility 

### ISSUE THREAD

**Issue by plolock** [Tarmslitaren/FrosthavenAssistant#168]
Tarmslitaren,

Im a ux/product designer that have recently started using x-haven. I can contribute with interface design improvements. Let me know if this is interesting. Of course its all in good faith and to contribute to the Frosthaven community!

Email me at niclas@undeco.se

**Comment by alexzhaohong** [comment]
I believe I saw your community feedback post on Reddit. Nice!

**Comment by Tarmslitaren** [comment]
Imma close this for now. In case there's need to itemize actual UI improvements, you are welcome to open new tickets ;)
