### ISSUE TITLE
Undo redo

### ISSUE THREAD

**Issue by msilve3466** [Tarmslitaren/FrosthavenAssistant#17]
Thanks for getting this app up and running. However, it seems that the undo button is not operational. Am I correct or are the four of us who are using the app creating user error?

**Comment by Tarmslitaren** [comment]
undo does not yet work while tcp wifi server/client connection is on.
Apologies for the inconveniece.

**Comment by Tarmslitaren** [comment]
due to the complexity of the state changes, I opted to do a blanket replace
whole state when connected. So the different state objects are in a way not
compatible. The good news is adding undo/redo is not that hard, I just
haven't done it yet.

**Comment by Tarmslitaren** [comment]
added functionality in 1.5.5
