### ISSUE TITLE
Character Modifier Deck Missing

### ISSUE THREAD

**Issue by shadowfax96** [Tarmslitaren/FrosthavenAssistant#174]
I can only see my character modifier deck in some scenarios, but in most of them it is covered up by a section adding button. 
![IMG_2399](https://github.com/Tarmslitaren/FrosthavenAssistant/assets/114513106/ffb8729f-df57-4f93-912c-76dcf7033000)

**Comment by Tarmslitaren** [comment]
Sorry, there's no character modifier decks implemented. some scenarios have allies, in which case an allies modifier deck will be visible to the right above the regular monster modifier deck
