### ISSUE TITLE
Feature request: Total round count

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#180]
In Frosthaven, quite a few scenarios have special rules that require players to count rounds from the time a section is read (usually when a door is opened).  Assistant handles these issues by resetting the round number to 1.  I'd love not to lose the count of previous rounds.   Perhaps the correct round number could be displayed?  Or if the "count of rounds since the event" is valueable to display, perhaps the round could be displayed as, e.g., `2 + 4`, where 2 is the round number in which the event occurs, and 4 is the number of rounds since the event?

**Comment by Tarmslitaren** [comment]
added in version 1.9.0. will show up in parenthesis in case it differs for the current round -8due to scenario special rules)
