### ISSUE TITLE
Settings not storing

### ISSUE THREAD

**Issue by lemonemone** [Tarmslitaren/FrosthavenAssistant#182]
My computer crashed mid-scenario, and I suddenly found my Windows Xhaven assistant v1.8.3 unable to retain any settings.

I updated to 1.8.4 and the issue was retained - my computer crashed in the middle of grabbing a Shrike Fiend, so I assume the settings file was corrupted, but I don't have a clue where it's stored.

Solution here is just "where is the xhaven assistant settings file located". Thanks!

**Comment by Tarmslitaren** [comment]
assuming windows. I don't remember exactly ( not at my computer ) but it's
likely <username>/appdata/local/frosthaven_assistant/ or similar.

you could go to your user folder and search frosthaven

**Comment by lemonemone** [comment]
It is Windows - what would the filename of the settings file that stores latest-session information be? Searching the user folder is a dead end.

**Comment by Tarmslitaren** [comment]
AppData\Roaming\com.tarmslitaren\frosthaven_assistant

**Comment by lemonemone** [comment]
That partially fixed matters - new issue's popped up of not being able to create a server that I can connect to, but hey, my settings work! Thank you very much for the help.
