### ISSUE TITLE
iPad version is very slow on animations since recent update 

### ISSUE THREAD

**Issue by KirstyGameDev** [Tarmslitaren/FrosthavenAssistant#183]
Playing the iPad version of the app since the update and finding the animations on the card draws are slow.

**Comment by Tarmslitaren** [comment]
Thanks, I'll look into it. I updated the flutter framework, and they have
changed the underlying rendering engine.

br,
Hans

**Comment by winningfaith81** [comment]
I too am having this issue. It seems very lagged when running animations since the update like I'm running out of ram, but I shouldn't be. 

Thanks!

**Comment by Tarmslitaren** [comment]
fix incoming (1.8.5) thanks for bringing it to my attention

**Comment by KirstyGameDev** [comment]
No problem. Thanks for the quick fix!
