### ISSUE TITLE
Headless Server for Frosthaven Assistant

### ISSUE THREAD

**Issue by nallroggen** [Tarmslitaren/FrosthavenAssistant#186]
Is there any way to implementation a headless server feature within the Frosthaven Assistant application. In more detail, to enable the app to function as a local server or simply automatically start the server on a local device. This would probably provide a more stable synchronization of data across devices.

**Comment by Tarmslitaren** [comment]
It's not within scope of the app, but you are welcome to fork the repo and create one yourself. I doubt it would improve stability by much, but would potentially  be more convenient to start than having to open up the app on device and start server.
I'll close this ticket now as out o scope
