### ISSUE TITLE
Bug in Forgotten Circles Challenge Scenario

### ISSUE THREAD

**Issue by badplatypus** [Tarmslitaren/FrosthavenAssistant#187]
In the last room of Tower to the Stars, it doesn't automatically add the Wind Demons .

**Comment by Tarmslitaren** [comment]
Thanks, I missed this. It's fairly minor as the wind demons are anyway
added in a previous room. Though for those groups which likes to remove
monsters between rooms it's still relevant.

**Comment by Tarmslitaren** [comment]
fixed in 1.8.7
