### ISSUE TITLE
Minor UI suggestion in Scenario 108

### ISSUE THREAD

**Issue by badplatypus** [Tarmslitaren/FrosthavenAssistant#188]
In Scenario 108, the text at the beginning says "Choose section.  (Bosses use separate decks)"  I would suggest adding "ability card" before "decks" to make the intent clearer.  (I'm assuming this was done because drawing 2 cards in a round from the same ability card deck would require a massive reworking of the code for that functionality and really isn't worth it for just this scenario.  This is a very reasonable compromise.  When I first read it, I thought maybe it meant the attack modifier decks.  Adding "ability deck" would clear up that confusion.)

**Comment by Tarmslitaren** [comment]
added in 1.8.7
