### ISSUE TITLE
Loot deck visual doesn't reset

### ISSUE THREAD

**Issue by dfannius** [Tarmslitaren/FrosthavenAssistant#19]
Release 1.5.2, macOS.

Setup: Choose a scenario from the hamburger menu. Draw a few loot cards. Choose the scenario again.

Observed: The appearance of the loot deck still looks like the old state (there's a discard pile and the size of the draw pile is smaller), although its actual state does seem to be successfully reset (when I draw a new card there's only one card in the discard pile).

Expected: The appearance of the loot deck is reset (no discard pile, full-size draw pile).

Also, if there's a better way to reset the loot deck, let me know; I didn't notice one.

**Comment by Tarmslitaren** [comment]
Thanks for reporting! This is a bug. You can get around it by changing window size ( or orientation on mobile ) while I make a fix.

**Comment by Tarmslitaren** [comment]
Fixed in version 1.5.3
