### ISSUE TITLE
Add "retry" action text to "lost connection" toast

### ISSUE THREAD

**Issue by brandon-mork** [Tarmslitaren/FrosthavenAssistant#191]
**Minor quality of life improvement:** Add "Retry" action button to "lost connection" toast. (Bonus: change "lost connection" toasts from teal to red, to make it more obvious when device has disconnected.)

**Why?** Reduces four clicks down to one click: replaces need to click into settings, scroll down, click "Connect as client", and click out of settings.

With 5 devices (one host and 4 clients), over the course of a session our group must reconnect devices to the host a few dozen times. Many times per scenario we'll all think we're waiting for someone to submit their initiative, but it turns out they're disconnected and didn't realize it. Having a "Retry" button on the "Lost connection" toast would save us many clicks and much frustration!

**Comment by brandon-mork** [comment]
@Tarmslitaren any estimate on when this already-merged feature can be released? :)

**Comment by Tarmslitaren** [comment]
yeah -:)

I'll try to get a new update out before Christmas. Sorry for the delay.

It will have mostly data fixes, and hopefully the refactoring done will not
break too many things.

**Comment by brandon-mork** [comment]
Hooray -- happy holidays!

**Comment by Tarmslitaren** [comment]
release today. Couldn't make Xmas due to a combination of dependency hell and interference from the steve jobs ghost of xmas. Happy new year!

**Comment by brandon-mork** [comment]
Thank you for all of your hard work creating and maintaining this excellent app! Happy new year!
