### ISSUE TITLE
1.8.6 on play.google.com but not in github releases

### ISSUE THREAD

**Issue by eNTi** [Tarmslitaren/FrosthavenAssistant#193]
What's going on there? I'm a bit suspicious.

**Comment by Tarmslitaren** [comment]
Had to do a simple update to just upgrade the flutter framework, just for
android, due to some google policy (need to taget android 13). Didn't think
it worth putting a release in github for. (In hindsight I wouldn't have
needed to update the version either, but you live, you learn)

br
Hans

**Comment by Tarmslitaren** [comment]
Shouldn't be any problem. the release jumped, because there was also a ios
only bug a while ago.

**Comment by eNTi** [comment]
Thanks for the answer and the amazing work our are doing.
