### ISSUE TITLE
Monsters out of order?

### ISSUE THREAD

**Issue by badplatypus** [Tarmslitaren/FrosthavenAssistant#195]
When opening a new room in Forgotten Circles scenario 106, the monsters seem to have been displayed out of initiative order.  I think they appear after the Nightshroud because the Nightshroud opened the door (which is nice functionality, BTW---is that in fact how it works?), but I don't understand why the Wind Demon at 21 is showing up before the Frost Demon at 18 and the Avatar at 19.
![IMG_5879](https://github.com/Tarmslitaren/FrosthavenAssistant/assets/65642601/089f41b1-6df6-4ec0-b9c2-fd57752ecc90)

**Comment by Tarmslitaren** [comment]
fixed in version 1.9.0
