### ISSUE TITLE
Feature request: random dungeon deck monster cards

### ISSUE THREAD

**Issue by badplatypus** [Tarmslitaren/FrosthavenAssistant#196]
Would it be possible to have in the "Add Monsters" tab an option to automatically add the correct number and type of monsters based on the number of characters from a random dungeon deck monster card?

And for any scenarios that are built off of these (I believe there's one each in Gloomhaven and Forgotten Circles; I don't know about Frosthaven), it would be nice if there were tabs at the bottom with the possible monster types to be added (like the tabs for adding monsters that appear in a certain section of the Scenario Booklet).

**Comment by Lurkars** [comment]
This is a cool idea.

@Tarmslitaren I will add those cards just as section data, so one can add it as section from menu. If you want to adopt it, I think you have working parser for that stuff right? So you can also think about it as easy migration when I'm done.

**Comment by Tarmslitaren** [comment]
feature added in version 1.9.0. From set senario menu, select campaign Gloomhaven, Frosthaven or Forgotten Circles. Then you may select the 'Random Dungeon' scenario. 3 dungeon populaton cards will be randomly selected for you.
