### ISSUE TITLE
Algox Priest does not have enough standee numbers

### ISSUE THREAD

**Issue by proteininja** [Tarmslitaren/FrosthavenAssistant#20]
Algox Priest only goes up to 4 in the app, but the physical game has six standees.

Thank you for this wonderful app! My wife and I don't really consider the game playable without an app of this sort and the official one isnt out yet. You are the best!

**Comment by Tarmslitaren** [comment]
Thanks! I'll fix it soon(tm). Looks like the old monster spoilers were outdated.

**Comment by proteininja** [comment]
I have a physical copy now. If you want me to double check anything let me know.

**Comment by Tarmslitaren** [comment]
if you feel like double checking the standee amounts for the other non boss
monsters, that would be really nice. I don't have the game yet and it's
hard to see on any picture. I used the old monster spoiler page from
Cephalofair's webpage, but it's outdated.

**Comment by proteininja** [comment]
I'm sorry this isn't like a spreadsheet or something but I'm trying to avoid spoilers and I don't know the names of the monsters so I'm using pictures of the standees. The most common number of monsters is six. All the photos in this album are of monsters that do not have a number of six. One of the pictures is of all the monsters with two. The next is of all monsters with four and the final is of all monsters with 10.

Let me know if you have any questions or you can't make out the monsters image for any of these.

https://photos.app.goo.gl/vHmFUqU92fvvXM5V9

**Comment by Tarmslitaren** [comment]
Awesome, thanks!

**Comment by Tarmslitaren** [comment]
Fixed in latest version (1.5.3) along with a few more standee amount errors. Thanks again!
