### ISSUE TITLE
Scenario 110 (Guardian's Temple): spawns are too infrequent

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#200]
The special rules for Scenario 110 say,

> At the start of each round after the first, spawn one Ruined Machine at d. It is normal for two characters, elite each second spawning for three characters, or elite for four characters.

We just played the scenario, and XHA is not spawning the Ruined Machine every round. A look at [`Frosthaven.json`](https://github.com/Tarmslitaren/FrosthavenAssistant/blob/main/frosthaven_assistant/assets/data/editions/Frosthaven.json) suggests that the app is spawning every _other_ round.

**Comment by Tarmslitaren** [comment]
fixed in 1.8.7
