### ISSUE TITLE
Bug: Input for connection to server does not allow any other subnets then 192.168.1.xxx

### ISSUE THREAD

**Issue by reckter** [Tarmslitaren/FrosthavenAssistant#201]
I have a setup where all local IPs are in the 10.0.0.xxx subnet. The input however does not allow me to input this. It always jumps back to 192.168.1.xxx.

It should just allow all IP addresses, which would also add support for VPNs such as tailscale etc.

**Comment by Tarmslitaren** [comment]
You may now choose ip form a list 

fixed in version 1.9.0

reopen if this is still causing problems
