### ISSUE TITLE
Under the Ice Scenario Rule Bug

### ISSUE THREAD

**Issue by salesforce-john** [Tarmslitaren/FrosthavenAssistant#204]
Special Rules indicate additional enemies don't spawn until after the Steel Automaton is killed.

Current functionality has them summoned on regular round tracking.

**Comment by Tarmslitaren** [comment]
I cannot reproduce. Did you tap the '1' section by mistake? Or do you have an earlier version?

**Comment by Tarmslitaren** [comment]
No reproduction, closing.
