### ISSUE TITLE
Can't start server on Mac after update

### ISSUE THREAD

**Issue by frodriguez8705** [Tarmslitaren/FrosthavenAssistant#206]
I get the attached error when trying to set the Mac as a host. I originally had the ip set statically and changed it to DHCP thinking that was the issue but it still persisted. Tried redownloading the client a few times just in case. Tried different networks also. The iPhone app can start the server with no issue on the newest release. the 1.8.4 release still seems to work fine so we used that instead. Any ideas of what to try? Running MacOS Monterrey 12.6.8
<img width="1280" alt="Screen Shot 2023-12-29 at 3 44 24 PM" src="https://github.com/Tarmslitaren/FrosthavenAssistant/assets/155197266/a7e032a1-ac99-4057-8c46-f68c51d116b5">
<img width="1280" alt="Screen Shot 2023-12-29 at 3 44 37 PM" src="https://github.com/Tarmslitaren/FrosthavenAssistant/assets/155197266/a8bac7a9-1546-4653-a98e-37009db57862">

**Comment by Tarmslitaren** [comment]
Thanks!  I found the reason. Some of the app privileges got removed by mistake. I'll make a fix tomorrow.

**Comment by Tarmslitaren** [comment]
new mac build uploaded (same release 1.8.7)
