### ISSUE TITLE
Two Forgotten Circles Scenario 113 issues

### ISSUE THREAD

**Issue by badplatypus** [Tarmslitaren/FrosthavenAssistant#208]
There are two issues with Scenario 113:

1. The tabs for Section 30 and 108 are reversed; 30 should add 2 Elite Living Bones and 4 regular Deep Terrors and 108 should add 2 Elite Deep Terrors and 4 regular Living Bones.

2. The Seals are not added.  My suggestion would be to label them as "Seal of xxxx (J1b)", etc., and add each as the appropriate section is revealed.

**Comment by badplatypus** [comment]
Addendum: The first one is actually a known issue in the first printing (per the [Official FAQ for Forgotten Circles (first printing)](https://boardgamegeek.com/thread/2099479/official-faq-forgotten-circles-first-printing) on BoardGameGeek; search for "113" on the page) that was corrected in the second printing.

**Comment by Tarmslitaren** [comment]
fixed in version 1.9.0
