### ISSUE TITLE
Apostrophes cause player names to glitch

### ISSUE THREAD

**Issue by lamsorsen** [Tarmslitaren/FrosthavenAssistant#21]
Hello, thank you for making this app! We’ve played three scenarios of Frosthaven with it so far and for the most part it worked superb!

We did notice an issue when someone tried to put an apostrophe (‘) in their characters name while online play was active. 

Steps to reproduce:
1. Add a character on the server. Name them “Test’s”
2. Connect the client to the server.

The glitchiness is a little inconsistent. Once it caused a crash, and the app kept crashing every time we tried to open it back up. Most of the time the name just doesn’t show up on the client.

**Comment by Tarmslitaren** [comment]
fixed in 1.5.5
