### ISSUE TITLE
Suggestion: Remove/Hide Ally Deck

### ISSUE THREAD

**Issue by theM0rzan** [Tarmslitaren/FrosthavenAssistant#215]
This a small thing, because when added accidentalty, I can always click Undo to hide it, but could an option to hide the ally deck be added?

**Comment by Tarmslitaren** [comment]
Can you give more information on why you want this? There's already a setting to disable both modifier decks, why single out ally deck?

**Comment by Tarmslitaren** [comment]
fixed in version 1.10.1

if ally deck added fron side menu, it can now be removed from same place.
