### ISSUE TITLE
Feature request: Shuffle unrevealed cards only

### ISSUE THREAD

**Issue by sczyz92** [Tarmslitaren/FrosthavenAssistant#216]
There are many circumstances that we want to know what initiatives the enemy is capable of, and what those initiatives entail, without spoiling the draw order. Currently the only option is to shuffle the entire enemy deck without being able to specify specific cards to keep out of the shuffle. It would be a very appreciated feature to be able to view all cards in the enemy deck at the same time, and then reshuffle the undrawn cards only.

**Comment by fishhead1982** [comment]
This sounds like a great idea, we've had the same problem a few times in the past and ended up going to the physical copy to take a look.

**Comment by Tarmslitaren** [comment]
added this option in version 1.10.1

from card menu ( amd or monster ability) tap an undrawn card and choose 'shuffle un-drawn cards'
