### ISSUE TITLE
Boneshaper Raging Corpse Summon not in list

### ISSUE THREAD

**Issue by Taxeon** [Tarmslitaren/FrosthavenAssistant#218]
Skeletons ( Two versions?), Wraith, and several I guess I have yet to unlock exist but not. The L2 Raging Corpse, had to put it in as a custom. 

By The Great App and thanks for your clarifications on my stream (Active Minds Gamer)

**Comment by Tarmslitaren** [comment]
To reduce clutter ( and spoilers for those who prefer not to know upgrade cards ) Only summons that are available at the character's level is shown. Did you forget to set your boneshaker level to 2?

**Comment by Tarmslitaren** [comment]
I believe there are just so many different small features like this and many different ways that people engage with the app. Where the app is lacking most is in documentation or tooltips. In any case, all feedback is valuable. Happy Havening!
