### ISSUE TITLE
Crystal Enclosure Ice Pillars change HPs between rooms

### ISSUE THREAD

**Issue by Taxeon** [Tarmslitaren/FrosthavenAssistant#219]
In Crystal Enclosure scenario: So that is weird the math is (2+L)xC/2 for Pillar HP. In Room one it seemed to calculate correctly at 7 but in room two it went up to 8.

L is 3
C is 3
So ( 3+2) x (3/2) = 5 x 1.5 = 7.5 rounded down=7

**Comment by Tarmslitaren** [comment]
There is actually a different formula for room 2.

room 1: (2+L)xC/2
room 2: 4+(LxC)/2

so purely mathematical, it would be correct at 7 in room one and 8 in room two, however it is possible that the intent is to add 4 before dividing, meaning room two would be 13/2 = 6. I will ask for clarification.

**Comment by Taxeon** [comment]
Yea, sorry about that. I saw that in my second attempt. Still need the boneshaper Corpse summon though 🙂
________________________________
