### ISSUE TITLE
Intended use of the loot deck not quite clear

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#22]
We’ve tried the Frosthaven loot deck, and we have no problem turning over cards or seeing all the cards that have been turned.  But we can’t find a mechanism to associate loot with a character.  We don’t want to just update the character’s resources, since if we lose the scenario we may not get to keep them.  Do you have any suggestions? Is something planned for the future?

**Comment by Tarmslitaren** [comment]
I would record by the character resources and make a note of what was before, in case the scenario is lost.

 I might add loot per character tracking at some point, but it would mean you would either need to be careful to mark current character turn, or need to spend more time setting which character is looting.

**Comment by sigismond0** [comment]
We've just been using it for draws, and tally marking our character sheets as we draw.  Agree that a counter in the app for this scenario's loot on each character would be nice, but also agree that it'd either be super clunky (lots of clicks) or easy to mess up (draw the loot on the wrong turn).  Secretariat has this, and that's exactly how it works there to mixed effectiveness.

**Comment by Tarmslitaren** [comment]
added character icon to the cards added during a character's turn
