### ISSUE TITLE
Scenario 21: First Room Monsters Incorrect (4-player)

### ISSUE THREAD

**Issue by scottmk** [Tarmslitaren/FrosthavenAssistant#224]
In the 4-player version of Scenario 21, for four players, the first room incorrectly sets up two Living Spirits, when it should be three

**Comment by nicholaskillin** [comment]
@scottmk Thanks for pointing this out. This issue has been fixed and I'm guessing will be included in the next release.

**Comment by Tarmslitaren** [comment]
yes this will be fixed on next release

**Comment by Tarmslitaren** [comment]
fixed in 1.9.1
