### ISSUE TITLE
Forteller Download Location

### ISSUE THREAD

**Issue by j-ribs** [Tarmslitaren/FrosthavenAssistant#225]
Hello, I am trying to add the foreteller audio to a soundboard so I can play it over discord, where are the forteller audio files downloaded to?

**Comment by Tarmslitaren** [comment]
This is a feature from the tts mod version of the app so I have no idea.
Better check with gudyfr the guy behind that one. I would wager a guess
that the download location is a default download location that is different
depending on platform. In any case you may want to check the terms and
services for forteller, if copying those files around is allowed.

**Comment by j-ribs** [comment]
Oh right, thought i was on that github, ill check there, thanks.
