### ISSUE TITLE
Modify hit points by sliding right/left (GHH feature)

### ISSUE THREAD

**Issue by tscrib** [Tarmslitaren/FrosthavenAssistant#23]
Suggestion:
Back when GHH existed, I used to slide right and left (or click and drag) over characters and monsters to adjust their hit points. (Could also slide right/ left near the right edge of characters to modify experience).

I used this every turn. 

It also allows the user to stay on the main view, and not have to open a window (stat modification).

Anyway, it is a minor usability point, but one which would greatly improve my quality of usage. 

Thanks again for all your hard work!

**Comment by HDCharles** [comment]
This, also drag initiative was super useful

**Comment by borisv1307** [comment]
I third this feature request, please. Thanks for all your work on this!

**Comment by SaschB** [comment]
This is my most wanted feature, I wish I knew how to implement it. I'd be interested in hearing from @Tarmslitaren whether this is technically feasible but low priority, or extra complicated for some reason.

**Comment by Tarmslitaren** [comment]
I hear you. I don't know the best way to implement this, or if drag feature is the best solution for fast health change, so some research needed. It is slated for next major release, whenever that will be (within a couple of months probably. )

**Comment by Tarmslitaren** [comment]
done in 1.7.0

**Comment by borisv1307** [comment]
I just downloaded the new release and tried (on Windows 10). No luck. Perhaps I am being dumb?

**Comment by Tarmslitaren** [comment]
om characters, drag right or left from the health text,
on monsters drag left or right from the monster box.

**Comment by SaschB** [comment]
> on characters, drag right or left from the health text,

Why not allow dragging from the entire character box? Adjusting health is one of the most common actions in the game. Targeting only the relatively small health number seems unnecessarily restricting, and there's no other action associated with horizontal dragging, right?
