### ISSUE TITLE
Feature request: reminder about battle goals

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#231]
My group quite often forgets about battle goals.  Sometimes we remember when the scenario is already well underway.

I'd love to have an option in Settings that would make X-Haven Assistant launch a popup, "Have you chosen battle goals?", when the Draw button is clicked for the first time (before round 1).

**Comment by fishhead1982** [comment]
Seconded. Also if you could have the effects of some of the battle goals added to the monsters or monster attack deck that would be so good.

**Comment by Tarmslitaren** [comment]
added in version 1.10.1
