### ISSUE TITLE
Reveal Attack Modifier deck and re-order bug

### ISSUE THREAD

**Issue by dcantatore** [Tarmslitaren/FrosthavenAssistant#24]
When you use the diviner to reveal the attack modifier deck and re-arrange the order/send to bottom the order does not persist.

**Comment by Tarmslitaren** [comment]
I was not able to reproduce this. remember that addi g curses/ blesses to the deck triggers a shuffle so the ordering gets lost. same for next round if x0 or x2 has been drawn. 

If this was mot the case, can you give more serial on how it happened?

**Comment by dcantatore** [comment]
When you play a card for diviner and it is your turn in the round you need to reveal the top 6 card of the attack modifier deck which you can do. 

Then you can drag them around (or send to bottom - which i'll address shortly). After doing such and pressing close, if you re-opened it and pressed reveal top 6 cards they would not be in the order you set them as.

Also with the place up to 3 on the bottom there is no way to ensure the order and the order matters for this as well. They would need to stay revealed.

**Comment by Tarmslitaren** [comment]
Still cannot reproduce.

you are correct, the cards sent to bottom should remain revealed. I'll add that to the backlog

**Comment by dcantatore** [comment]
Let me see if I can get a screen recording for you

**Comment by Tarmslitaren** [comment]
are you using the connect to other devices feature, when this happens?

I did now notice undo scrambles the deck :( I suspect similar would happen when online.

**Comment by dcantatore** [comment]
I was doing this across the sharing/connect to other devices, maybe explains why I can't reproduce solo today. Might also be worth checking this doesn't happen to enemy ability decks in the same situation. 

*There may be a bug that had to do with the reshuffle at end of round with 2x and null being in the discard and the timing of re-ordering the cards and pressing the draw button. See video. 


https://user-images.githubusercontent.com/15852431/208964615-605926f7-336f-44e5-8b2a-704257e81a58.mp4

**Comment by Tarmslitaren** [comment]
fixed for next version
