### ISSUE TITLE
No way to reveal enemy ability cards - rearrange/send to bottom

### ISSUE THREAD

**Issue by dcantatore** [Tarmslitaren/FrosthavenAssistant#25]
When playing with the diviner you can not reveal the enemy cards to re-arrange them such as card Preordain path bottom half, and many others.

**Comment by Tarmslitaren** [comment]
you can't reveal during draw phase, but you should be able to during the round

**Comment by dcantatore** [comment]
How do you do that in the app?

**Comment by Tarmslitaren** [comment]
tap the enemy ability card. it opens a card menu where you can see the cards similar to the amd deck menu.

**Comment by dcantatore** [comment]
Thanks! didnt notice that was possible

**Comment by Tarmslitaren** [comment]
no problem! Happy to help.
