### ISSUE TITLE
Various Issues after a few plays

### ISSUE THREAD

**Issue by GarrettChan0** [Tarmslitaren/FrosthavenAssistant#26]
I'm really enjoying the app, so thanks very much for making it. I asked some questions on reddit and you replied to me before, but I assume reporting issues here is better.

1. Scenario 28 should have Allies Modifier Deck.

2. Probably you need a feature to switch Normal and Elite monsters due to a certain ability of Ice Wraith.

3. Ice Wraith again, probably you can somehow hide the "Normal: Range 4" if there's no Normal Ice Wraith present.

4. Ice Wraith again again, Scenario 65, there's a named Ice Wraith with this mode switching, and it's very confusing. Maybe there's a better way to show with the app.

5. Normal Lurker Soldier somehow has 2 Pierce abilities.

6. If there's a special rule for the scenario, it will keep showing the banner even if switching into another scenario, and maybe the banner need to push things to a different layer or position. Now it covers the Allies Modifier Deck as well.

7. If a scenario features objectives (eg: Scenario 115, or Section 66.1, can't think of others for now oops), if you click the HP of the objectives, they are showing the wrong level. (1 higher than scenario level)

8. Section 89.1, the Elemental Anchor should have initiative of 1, but not sure whether you can assign it by default.

I'll keep using it and report any further things I find. Thanks :)

**Comment by Tarmslitaren** [comment]
Thanks for reporting! I'll fix most of these. Hiding normal: text would be a bit of a hack, so probably won't fix for such a small improvement. 

Banners can be tapped away, so it's not much of an issue, but I'll look into it.

The others I will deal with for sure.

**Comment by GarrettChan0** [comment]
Sure no problem. It's more like the Ice Wraith is coming with a new mechanics so it confuses me a bit. I think it's nice to look like that, but if that's too much work to do, it's all fine.

I forgot one yesterday, so I put in the number 7.

**Comment by Tarmslitaren** [comment]
I don't see that rule in 89.1 about initiative 1?

**Comment by GarrettChan0** [comment]
oh whoops... obviously it's not this one. I think I saw one but I'm not sure whether the app is correct or not. I have to double check again. Sorry about this.

**Comment by GarrettChan0** [comment]
Well, I found it, it's 75.2 (not implemented), but in the meantime, it starts with something 99, but they'll become something 1... I'm not sure whether you can do anything about it except the player punching it in manually.

**Comment by Tarmslitaren** [comment]
I can really just add starting initiative. then the players will need to
change manually. It's very unusual for initiative to change for these
objects/escorts.

**Comment by Tarmslitaren** [comment]
all except 7 fixed in 1.5.5
