### ISSUE TITLE
Frosthaven Scenario 36 door hp calculation

### ISSUE THREAD

**Issue by proteininja** [Tarmslitaren/FrosthavenAssistant#29]
In Frost Haven scenario number 36 there are four doors a through d. The scenario states that each doors hit points are equal to. ((C-1)/2)x(L+3) rounded down

I've noticed that your application seems to usually calculate the health of bosses and objectives correctly so I assumed that there was some type of calculation taking place here. In our campaign we have two characters and we are currently at scenario level 2 so I calculated the hit points of each door to be two.

The app is calculated the hit points of each door to be four. I did not know whether I made a mistake or whether there is no calculation in the app and that I should manually adjust all the HP's or if there is an error in the app. I figured I'd bring it to your attention.

**Comment by Tarmslitaren** [comment]
Thanks! turns out the formula was rounding prematurely

**Comment by proteininja** [comment]
I think that there is still an error. I set the scenario today I imagine
you must have pushed out an update and now the door healths are calculating
to five. It should be half that rounded down. Character minus one for two
players would be one divided by 2 is 1/2 *5

**Comment by Tarmslitaren** [comment]
Sorry for the confusion: I haven't yet releases an update with the fix,
since I'm gathering a bunch of other important fixes with it. expect an
update in 2-3 weeks or so.

**Comment by Tarmslitaren** [comment]
fixed in 1.5.5
