### ISSUE TITLE
Suggestion for usability improvements in undo/redo

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#3]
I want to begin by saying that the work is terrific and we are really glad to have the app.  But I would also like to suggest trying to improve the usability of the undo/redo feature.

Today I got confused and applied monster attacks to the wrong figures on the board.  We caught it fairly quickly but I needed to revert and replay the last three attacks.  In the end I just couldn’t do it, because the current undo/redo display did not give me any hint about _where_ I was in the transaction log. So I couldn’t really figure out where I was and when to stop undoing.

I grant you that a calm, collected user could probably have worked it out.  But it is hard to stay calm and collected when (a) I have just screwed up the party’s health points and (b) monsters are trying to kill me.

Here are a couple of ideas:

  - It might be helpful to see about two actions’ worth of context on either side of the transaction pointer, for a total of maybe six: the action I’m about to undo, and the next two actions that will be undone if I continue clicking. Plus the last two or three actions I have alread undone.  But it may be that screen real estate is too tight for this change.

  - Something easier to do is to provide more information about each transaction.  For example, instead of “health change,” the app could say, “-2 to Brightspark health.” That alone would probably have been enough to get me out of my panic this afternoon.

In any case, thanks for the great app!

**Comment by Tarmslitaren** [comment]
Adding more information in undo's for the next release. Thanks for doing reports, it's very helpful!
