### ISSUE TITLE
Feature Request - Character Token Markers

### ISSUE THREAD

**Issue by sigismond0** [Tarmslitaren/FrosthavenAssistant#31]
Some characters (Notably Hatchet and Angryface) have the ability to place character tokens onto monsters to mark them for effects.  Several other classes can do this to a lesser extent.  It would be nice to have some way to mark this on enemy standees through the condition list.  Character icons would be ideal, but even just a 1/2/3/4 marker would be sufficient.

**Comment by SaschB** [comment]
This would also benefit (at least) one starting class from Frosthaven.

**Comment by Tarmslitaren** [comment]
added in 1.8.0
