### ISSUE TITLE
Server Reconnecting

### ISSUE THREAD

**Issue by sigismond0** [Tarmslitaren/FrosthavenAssistant#32]
In its current implementation, the server must be re-started whenever the app is launched, and every client must re-connect.  All of these settings are currently buried behind Menu->Settings0>scroll to the bottom->check a box->tap out.  Not very user friendly to require that many clicks every game just to get started.

A "Launch Server" button in the main menu, and "Reconnect to last server" would be ideal.  Alternatively, a "Connect to Server" button in the main menu could pop up a prompt that shows the last connected server settings (allowing you to change if needed) and a checkbox to connect like the setting menu shows.  The Launch Server button could also work similarly.

**Comment by nrnrnr** [comment]
Agreed.

**Comment by Tarmslitaren** [comment]
added in 1.5.5
