### ISSUE TITLE
Mouse Scrolling Slow

### ISSUE THREAD

**Issue by sigismond0** [Tarmslitaren/FrosthavenAssistant#33]
As discussed on reddit, mouse scrolling seems to be bugged to scroll at a fraction of the expected speed on Android.  Probably not a high priority.

**Comment by Tarmslitaren** [comment]
it's not very fast on pc either, so it will be looked at soon. There might
he an issue with the framework using same events for trackpad, meaning
fixing the mousewheel scrollspred might screw with trackpad usability.

**Comment by Tarmslitaren** [comment]
fixed in 1.6.0  Latest flutter version 3.7 fixed it.
