### ISSUE TITLE
Conditions don't always expire

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#35]
Sometimes, when passing turns, conditions don't expire. This usually happens when we pass turn *to* someone instead of ending the current turn (example, 3 characters, character 1 or 2 have conditions, and we click the portrait for character 3)

**Comment by Tarmslitaren** [comment]
Can you give steps how to reproduce? (remember if a condition is added during a characters turn it will not expire until the end of their NEXT turn)

**Comment by mentonin** [comment]
It definitely wasn't about conditions applied on their turn. I can't reproduce it every time, but it happened a few times, inconsistently. I'll try to reproduce it reliably, but I think it might be related to sync (I haven't experienced it when not connected)

**Comment by mentonin** [comment]
I managed to reproduce at least one bug:

1. Have a character play last
2. Draw initiatives
3. Give the last character an expirable condition
4. Pass *to* their turn clicking their portrait once
5. Click "next round"
6. Condition isn't expired

Doesn't happen on monsters (and I'm sure something similar happened with monster conditions when I was playing, so I think there may be other bugs)

**Comment by Tarmslitaren** [comment]
Can confirm bug if character last, has condition, clicked once to make current and then next round clicked - does not remove condition

**Comment by Tarmslitaren** [comment]
fixed the issue for character last in list not expiring conditions if press next round. version 1.5.5
