### ISSUE TITLE
Input HP/damage

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#39]
When changing large amounts of HP at once, clicking dozens of times is inconvenient. If I could tap somewhere and input HP it would be better for things like some of lighting bolt's actions

**Comment by Tarmslitaren** [comment]
Agreed it's nice to have a way to more quickly change the health values. Even better if it can be done without opening the status menu. The ghh way of drag left-right to change the value has been requested, but I'm not so sure that is the best experience.
Requires more thought.

**Comment by mentonin** [comment]
I think sliding feels good, specially with haptic feedback, but it doesn't fulfill the need for changing big values. For this, I can think of 2 interfaces:

1. Long press on figure opens up HP input (or, maybe, input value and press a button to add/subtract)
2. Long press on figure opens up the figure edit menu (where you can change lvl and max HP). Max HP can now be typed in. Current HP is also shown and can be typed in

**Comment by DaChango** [comment]
I have implemented a functioning version of the health sliding function (currently only to characters). Hope it is a start to fixing this issue!

**Comment by Tarmslitaren** [comment]
Bad timing! 😅 I just finished implementing the whole feature yesterday. It has a visual  horizontal scroll wheel that pops up on horizontal drag from the monster box or character health text. 

I might still need to tweak the speed but it's otherwise complete.

**Comment by Tarmslitaren** [comment]
Implemented similar to ghh in 1.7.0
