### ISSUE TITLE
Cannot figure out how to add -1 cards to the monsters’ attack-modifier deck

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#4]
We recently got a road event which gave us the right to add two -1 cards to the monsters’ attack-modifier deck for the entire scenario.  After looking through the app and following the “Documentation” link, we could not figure out how to do it.

Is this a feature that has yet to be implemented, or is it just well hidden?

We are using the “early access” 1.0 beta through Google Play Store.

**Comment by Tarmslitaren** [comment]
That's an oversight on my part. Ill fix it. In the mean time, the functionality does exist, but only when you add Diviner as a character. It's in the modifier card menu, opened from the enemy modifier discard pile.
