### ISSUE TITLE
Wrong hazardous terrain damage

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#40]
Hazardous terrain damage is wrong for difficulties 3, 5, and 7

**Comment by Tarmslitaren** [comment]
It's using Frosthaven rules: 1,2,2,2,3,3,3,4 is correct.

**Comment by mentonin** [comment]
Why is it using Frosthaven rules if I'm playing a Forgotten Circles scenario? GH rules are half of trap rounded up

**Comment by Tarmslitaren** [comment]
Because Frosthaven rules are better ;). I could add an option to use
gloomhaven rules which will affect marking summons, hazardous terrain
calculations and solo mode.

**Comment by mentonin** [comment]
I think the sensible option would be to use GH rules for GH scenarios and so on, and opt-in to "backport" rules through options (could have a menu for this and other house rules). House rules should generally be opt-in, not opt-out
