### ISSUE TITLE
FC scenario 111

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#42]
Missing section 66 and section 67 apparently does nothing

**Comment by Tarmslitaren** [comment]
You are right, 67 does nothing except add monsters that were already present at start. I will remove it.
App does not handle changing of stats on the same monster type, so this special rule here is not implemented. I'd put this as a very low priority.

**Comment by mentonin** [comment]
Can't it be implemented as a new monster type?
The Husk (v2)

**Comment by Tarmslitaren** [comment]
yes, but, in addition I'd need to remove the old moster type and transfer
the monster instance from the old to the new. That's way to much for a one
off scenario special rule.

I suppose I could just add a v2, but then it would have to be named
differently and it would be awkward for the end user anyway.

**Comment by mentonin** [comment]
I think the simple v2 with updated stats is worth the trouble for the end user. They can transfer the monster manually, and the different name is not nearly as confusing as the different stats. I can do a PR if you agree.

Also, I opened a bunch of issues and am willing to work on most of them. I'm not good with UI, but I am willing to learn. But I don't want to work on features you wouldn't like to implement, so if you could tag which issues you find worth implementing, I can start tackling them.

**Comment by Tarmslitaren** [comment]
Ok cool! I'll assign some of these to you. 

I don't remember exactly now, but wasn't there even a v3 of this mini boss?

**Comment by mentonin** [comment]
There might be (we didn't open every section). I'll check all the sections and implement

**Comment by Tarmslitaren** [comment]
fix added in 1.5.5
