### ISSUE TITLE
Show only subset of conditions

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#43]
Some conditions shouldn't be shown all the time (e.g. Ruinmaw's Rupture should only appear when ruinmaw is in play; regenerate shouldn't show when playing base game). They could be filtered on scenario and characters in play

**Comment by Tarmslitaren** [comment]
rupture exist on an item as well. And you are able to play any campaign
with any class making this a much harder distinction to make. I don't know
but I wouldn't be surprised if regen is also on some item. I plan to make a
simple 'hide custom content' option for those that rather not see the extra
custom conditions and classes from crimson scales etc.

**Comment by mentonin** [comment]
Good point on items. There definitely exists at least one for Regen indeed. I actually submitted an issue for content selection like you said as well. I think this issue can be closed, then, in favor of the manual implementation
