### ISSUE TITLE
Don't remove monsters while editing

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#46]
When editing a monster's health, don't remove it as soon as its HP reaches 0. It would be better to hold onto the monster until the editing box is closed (and thus changes are confirmed)

**Comment by Tarmslitaren** [comment]
I don't think it's worth changing this. The app is designed to need minimal confirmation in mind in general, everything is applied immediately, and if something goes wrong you can undo. or reapply. Most of the time it's going to be trivial to recreate a standee if you happen to kill it by mistake even without using the undo feature.

**Comment by mentonin** [comment]
I dont think clicking out of the box is much added confirmation - in fact, it's the normal workflow when the monster doesn't die. Recreating is much more hassle, and requires remembering previous conditions. Undo is good, but unavailable when connected (and requires reapplying everything, instead of clicking a button once)

**Comment by Tarmslitaren** [comment]
I think the answer here is to wait for undo to be implemented for the connected state. Hopefully the wait will be quite short.

**Comment by Tarmslitaren** [comment]
closing as wont implement, since undo is added while connected ( version 1.5.5
