### ISSUE TITLE
Reminder for applying conditions

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#48]
Similar to what GHH had, flash conditions when relevant:

- Wound, regenerate at beginning of turn
- Poison, shield, brittle, ward, regenerate when damaged
- Poison, wound, brittle, bane when healed
- Bane at end of turn

**Comment by Tarmslitaren** [comment]
This is implemented already. The animations just doesn't show when connected.

**Comment by sigismond0** [comment]
Some other thoughts on this subject:

* Wound, bane, regenerate - Automatically apply damage if effect is present at start/end of turn.
* Poiosn, brittle, ward - Prompt after marking damage to ask if they need to be applied
* Automatic condition math - Just enter your attack/modifier damage, app does the math on poison/bane/ward automatically

GHH did the former, and it was pretty nice not having to remember wounds.  Secretariat has an option to prompt for damage modifying conditions, and it's also fairly nice.  Both are obviously a lot more work, so it's up to you to decide whether it's worth considering or prioritizing.

**Comment by Tarmslitaren** [comment]
fixed in version 1.9.0
