### ISSUE TITLE
Can't do section 132

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#49]
FC section 132 requires you to reveal an ability card, resolve it, then move it to bottom of the discard. The app lets you reveal the card, but not move it to discard. If you have the Diviner, it lets you move the card to bottom of the deck (which is usually functionally the same, though not quite if you play other cards that modify the ability deck).

**Comment by Tarmslitaren** [comment]
So what needs to be done is an option when tapping a card in the ability card menu, to move it to discard.

**Comment by Tarmslitaren** [comment]
draw extra card festure added in 1.8.0
