### ISSUE TITLE
FC Scenario 108

### ISSUE THREAD

**Issue by mentonin** [Tarmslitaren/FrosthavenAssistant#50]
There is supposed to be only one boss deck, and 2 cards should be revealed each turn. This is only a minor change, but it does change the bosses' behaviour slightly.

On a related note, section 37 has an ambiguous note about the decks, while sections 101 and 44 show no such note, even though the deck treatment is the same.

Lastly, sections 37 and 44 should have allies

**Comment by Tarmslitaren** [comment]
allies added.
