### ISSUE TITLE
Add Curse to Monster AMD with Standee Tracking Disabled

### ISSUE THREAD

**Issue by GoodBusiness4** [Tarmslitaren/FrosthavenAssistant#54]
This is more of a request than an issue. Currently, I don't see a way to add curses to the monster AMD with standee tracking disabled. Could this be implemented for those of us that like to track monster HP/Conditions on the board?

**Comment by Tarmslitaren** [comment]
There is a way: tap amd deck discard pile for amd menu. on too is option to add/remove curses and blesses among other things

**Comment by GoodBusiness4** [comment]
I should have figured this one out on my own. Thank you.
