### ISSUE TITLE
Gloom Envelope X [SPOILERS]

### ISSUE THREAD

**Issue by gdapchan** [Tarmslitaren/FrosthavenAssistant#56]
I don't see any way to add the Bladeswarm character.  You can see all the Character class in the file download here: https://cephalofair.com/pages/bladeswarm
This print and play character class was unlocked by finding the link above after solving the envelope X riddle.  Cephalophair sold copies of this character as part of the Frosthaven Kickstarter.

**Comment by Tarmslitaren** [comment]
It's slightly hidden. type in the whole name in the search bar to unlock it.

**Comment by gdapchan** [comment]
Thanks!
