### ISSUE TITLE
Monster and ally decka sometimes draw "shadow cards"

### ISSUE THREAD

**Issue by LukitschKD** [Tarmslitaren/FrosthavenAssistant#58]
Occasionally when drawing from the ally or monster deck only the visuals for a shadow appear.  Card number in deck decreases so it seems that a card is being drawn but the image for it is not showing up correctly.  During play of Frosthaven scenario 3 issue got so bad only 2 cards of the ally deck were not being drawn as "shadow cards"
![Screenshot_20230108-103520](https://user-images.githubusercontent.com/54919415/211205597-7d63e3d5-9237-4333-a55f-1453677ba448.png)

**Comment by Tarmslitaren** [comment]
What platform, and device this this occur on?

**Comment by nrnrnr** [comment]
I’ve seen this as well.  Android.  Shadow showed up on both the server and client (Nvidia Shield Tablet K1 and Google Pixel 6).

**Comment by Tarmslitaren** [comment]
Can anyone confirm if this only happens while connected? Trying to narrow it down

**Comment by nrnrnr** [comment]
We've only seen it once, and that one time we were connected.

**Comment by Tarmslitaren** [comment]
Can anyone confirm if this still happens? I've never been able to reproduce.

**Comment by nrnrnr** [comment]
> Can anyone confirm if this still happens? I've never been able to reproduce.

We haven't seen it again.

**Comment by Tarmslitaren** [comment]
I will close this now as it is an old issue that I can't reproduce. Likely related to old fixed bug

**Comment by dekarguy** [comment]
We just had this happen to us tonight for the ally deck. PC host, 3 devices connected, 2 iPhones, 1 Android.

The PC and one of the iPhones were able to see all the ally cards, the other 2 phones showed a shadow every time a card was pulled.

I tried a couple ways of reproducing it on my iPhone and got a 100% repro

1. Start X-haven Assistant on PC and iPhone
2. Host a server on PC and connect with iPhone (or reverse)
3. On PC, start a new scenario (Scenario 1 Frosthaven works), don't add any monsters
4. Click the ally deck on either device, note it is fine on PC, missing on iPhone
5. Repeat steps 3 and 4 but on the iPhone instead, note the cards appear fine


It seems like whoever hits Set Scenario gets the ability to see Ability cards, as well as PC clients

**Comment by Tarmslitaren** [comment]
does all your devices have same version 1.8.3?
last version I noticed there were duplicate graphics for the allies deck but with different cases ( ex: nullAttack-aliies.png and nullAttack-Allies.png ) and deleted the duplicates. This may produce issues when running with older version.

If this is not the case, then there's likely another bug related to this.

**Comment by dekarguy** [comment]
That was it, pc server was on 1.8.2, iOS device was on 1.8.3, thanks for the update! :D
