### ISSUE TITLE
Frosthaven Chaos Demons Crash

### ISSUE THREAD

**Issue by lamsorsen** [Tarmslitaren/FrosthavenAssistant#59]
When playing any scenario with Frosthaven with chaos demons using local wifi connection, the chaos demon monster action card deck gets progressively more and more cards in it until it crashes. Every round, the number of unflipped cards in the chaos demon action deck is multiplied. Deleting chaos demons from the app fixes the issue. The host is ios and the client is android.

**Comment by Tarmslitaren** [comment]
fixed in version 1.5.6
