### ISSUE TITLE
In Crimson Scales scenario 14 (Cultist Cave), the Living Bones are superfluous

### ISSUE THREAD

**Issue by nrnrnr** [Tarmslitaren/FrosthavenAssistant#6]
In Crimson Scales scenario 14 (Cultist Cave), the special rules call for the Cultists to summon Living Corpses instead of Living Bones. So you don’t actually have to provide the Living Bones for that scenario; they aren’t needed.

(If you are not interested in this level of detail, I’ll be perfectly happy. My day job involves incredible attention to detail, and I do enjoy getting software just right, with no extra or unwanted parts.)

**Comment by Tarmslitaren** [comment]
Thanks again. Every detail matters :)

Fixed for next version
