### ISSUE TITLE
Card number 1251 unreadable

### ISSUE THREAD

**Issue by christopherboote** [Tarmslitaren/FrosthavenAssistant#63]
Card number 1251, which is for Water Sprite, has truncated text (see image)
![xhaven](https://user-images.githubusercontent.com/60782113/212698317-5c7682c0-943d-4430-9f69-55054b9c2f16.png)

**Comment by christopherboote** [comment]
So elite they throw boomerangs (disguised as parentheses) at you 😬 !

Chris

On 16/01/2023 14:27, Hans Möller wrote:

> lol. Only happens when you only have elite water spirits.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/Tarmslitaren/FrosthavenAssistant/issues/63#issuecomment-1384146620
[2]

**Comment by Tarmslitaren** [comment]
yup for now. Obviously I'll have to fix it.

**Comment by Tarmslitaren** [comment]
fixed in version 1.5.6
