### ISSUE TITLE
Chaos Demons' ability deck will cause whole app to lag.

### ISSUE THREAD

**Issue by AlexKatros** [Tarmslitaren/FrosthavenAssistant#64]
Chaos Demons' deck will keep adding cards until it contains 32000+ cards
![Screenshot_20230116_174630](https://user-images.githubusercontent.com/14913760/212776512-78f47778-a783-476a-9a79-412a5d416e33.jpg)

**Comment by Tarmslitaren** [comment]
fixed in version 1.5.6
