### ISSUE TITLE
Bug - Beginning-of-round alert reappears on update

### ISSUE THREAD

**Issue by lamsorsen** [Tarmslitaren/FrosthavenAssistant#65]
Great work on the update! Connecting was so much smoother tonight! Where’s the tip jar?

New bug: We were playing Frosthaven scenario 114 - Work Freeze tonight on the new version of X-haven with three devices: iphone hosting and two android clients. At the beginning of every round, a blue alert near the bottom of the screen would appear on all three devices directing us to spawn some enemies, as expected. However, any time we would update a stat on one device (such as a monster’s health) the blue alert would reappear on the other two devices, even if we were already mostly through the round.

I’m unsure if this bug exists for all scenarios with alerts or if it was just this one.

**Comment by Tarmslitaren** [comment]
this should be fixed in hotfix update 1.5.6.
