### ISSUE TITLE
Ally AMD Does Not Shuffle

### ISSUE THREAD

**Issue by sigismond0** [Tarmslitaren/FrosthavenAssistant#66]
Found this bug in Bannerspear's solo quest today.  After hitting a crit/miss, the ally AMD pile stays in place between rounds.  Won't shuffle until you draw through.  Can replicate on scenario 1 as well.

Additional notes on Bannerspear solo quest--ally deck is not loaded by default (guards probably not marked as allies?  Had to spawn in another monster type and flag them as allies to get the ally AMD).  It also doesn't start the Vermling ability deck top card as noted in the rules.  Workaround there was to manually view all cards, sort, and then start the scenario.

**Comment by Tarmslitaren** [comment]
Thank you. I have a fix for these for next version. Which will have to come out soon, since the severity of the no shuffle bug is high.

**Comment by Tarmslitaren** [comment]
fixed in version 1.6.0
