### ISSUE TITLE
1.6.0 resolution issues

### ISSUE THREAD

**Issue by SirYaro** [Tarmslitaren/FrosthavenAssistant#67]
Hello Hans
Foremost, thank you for releasing the Linux version. It was like super early Christmas :) It made me really happy. I hope you keep releasing this version regularly.

I just installed it on android device (FydeOS) and on my Linux box, and I notice that if window gets big enough, all items on the center part of the screen just vanish. Exactly same behavior is observed on android and Linux. I can't provide many details on android since I don't have any usable tools there, but the issue *looks* exactly the same as the one on Linux.

So if window height is 630 or less, width is not limited (I checked up to 3800px), but if window height is 631+ when width can't be more than 1646. Otherwise, app looks like that:

![obraz](https://user-images.githubusercontent.com/5879723/215293536-c7fc60a7-7955-44d9-aa40-d267382a32f5.png)

one pixel less and it got back to normal:
![obraz](https://user-images.githubusercontent.com/5879723/215293579-50f91b4a-3b1f-4186-9d47-e54fa448dc6a.png)

Console doesn't provide any useful errors. Just one msg when content gone:
`flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'`

I have the impression there is something wrong with a feature that put content into multiple columns, but that is just a guts talking, and I can be totally wrong... :)

**Comment by SirYaro** [comment]
I wasn't able to replicate this issue on a tablet. But it might have to low specs to display resolution big enough to cause problems. Or anything else :) Idk

**Comment by Tarmslitaren** [comment]
your hunch is correct. it happens when the list scaling is low enough to fit 2 columns, but items are only in the first column.

**Comment by Tarmslitaren** [comment]
fixed in 1.6.1
