### ISSUE TITLE
1.6.1 initiative notification got broken

### ISSUE THREAD

**Issue by SirYaro** [Tarmslitaren/FrosthavenAssistant#69]
When client-server mode is enabled, notification that other party already enter it's initiative (in form of ?? on other clients screens) doesn't work anymore.
A newly connected client always gets "??" on all heroes, and nothing will change in that regard, no matter what people enter on their devices.
Example (tablet is a client)::
![1675004171828_resized](https://user-images.githubusercontent.com/5879723/215334980-f2396c78-e0e5-4dda-a9ba-2ba16beb7775.jpg)

**Comment by SirYaro** [comment]
It looks like this feature starts to work after the first round (from the second onward).

**Comment by Tarmslitaren** [comment]
fixed in 1.7.2. init was somehow not cleared when changing scenarios.
