### ISSUE TITLE
Shuffle monster attack modifiers? - iPad OS 15.6.1

### ISSUE THREAD

**Issue by AtomicTwills** [Tarmslitaren/FrosthavenAssistant#7]
Probably missing something obvious, but I can’t figure out how to shuffle the monster attack modifier deck when you get a 2x or miss with the reshuffle symbol. 

The monster ability decks seem to automatically reshuffle when the shuffle symbol comes up, but the monster attack modifier deck will just proceed through the entire stack of cards before automatically reshuffling.

**Comment by Tarmslitaren** [comment]
Attack modifier decks shuffle at the end of the round when a x2 or 0x has been drawn. As per the rules. 
It's a common misconception the Attack modifier deck should be shuffled immediately.

**Comment by AtomicTwills** [comment]
Like I said, probably something obvious.  Apparently I’ve been playing wrong. 🤦🏻‍♂️
