### ISSUE TITLE
Show monster standee color (elite/normal) after turn has finished

### ISSUE THREAD

**Issue by TylerHelmuth** [Tarmslitaren/FrosthavenAssistant#70]
Loved using X-Haven Assistant today, but struggled updating monsters once they had taken their turns since the standee colors were greyed out.   Although we could differentiate between normal and elite bc of the standee ordering, it would be nice if we could also see their colors even when the rest of the monster is greyed out.

**Comment by Tarmslitaren** [comment]
Yes that is a good suggestion and a bit of oversight on my part. I'll try to fix that for next version.

**Comment by Tarmslitaren** [comment]
fixed in version 1.7.0
