### ISSUE TITLE
Round counter

### ISSUE THREAD

**Issue by loosebits** [Tarmslitaren/FrosthavenAssistant#71]
Please consider adding a (resetable) round counter. There are numerous scenarios that have events that trigger on certain rounds or even a certain number of rounds after a door has been opened or some other event.

And thank you for all your efforts!

**Comment by sigismond0** [comment]
The round counter is already there in the bottom right where you draw the round's initiative.  So you always know what round it is, and just need to note when an action took place (e.g. round 7) then you'll know when it expires (e.g., two turns later on round 9).

**Comment by Tarmslitaren** [comment]
added the special reset and rules for the sceanrios that use that ( found 10 ) in version 1.7.0 closing this. If more sections that use this feature are found, please open a separate ticket
