### ISSUE TITLE
Various small things and maybe one features

### ISSUE THREAD

**Issue by GarrettChan0** [Tarmslitaren/FrosthavenAssistant#72]
Small things: (Hopefully these minor things are not annoying to report here. If it's not good to post an issue for these, please let me know if there's a better way to handle this.

Capitalizations:

1. Algox Icespeaker's "ice Wall" is not properly capitalized.

2. Ooze's "calculated Strike" is not properly capitalized.

3. Section 48.1 "realm of Endless Frost" is not properly capitalized.

4. Scout's "rancid Bolts" is not properly capitalized.

5. Abael Herder's "Heed The Pigs" is not properly capitalized. "The" should be in lower case. Sorry for the annoyance :<

---------------------------------------------------------------------------

Non Capitalizations:

6. Abael Herder's "Heed The Pigs" will not display the X+1 range when there's only Elite Herder(s).

7. Seeker of the Abyss' innate Target 2 is written in a weird spot, so it looks like has 2X attack power :P

8. If you type something in the search bar and remove it completely, the entries will be ordered in the wrong order.

9. Maybe the special rule banner should be shown before draw? Now it shows after draw, but many scenarios setup things at the start of the turn. Also, maybe an option to turn it off? I don't actually use it, but I just notice it while using the app.

10. Sometimes when Ice Wraith's "Switch Form" function is called, the action card will revert back to the printed card. I tried around, I think when the Elite ones are behind the Normal ones, this will confuse the app. For example:

Elite (No. 1), Normal (No. 3) -----> Switch Form (but the app doesn't re-order them) -----> Normal (No. 1), Elite (No. 3)
(Then this will cause the card to revert back to the printed card, but it seems whenever you switch form and it re-orders, then it looks a bit annoying. No sure how do you implement this and no mess up everything...)

---------------------------------------------------------------------------

One feature I want, but not necessarily good, so please tell me what you think as I think it's probably a lot of work... I think it's how Gloomhaven Helper works, but I can't check now.

11. After drawing, if one type of monster is all dead, then the action card will be flipped down and the whole monster bar will be moved to the end with others that don't have a monster. I hope the action card is only greyed out and stay at the same spot in this case. Then, whenever the player hits "next round", it will move to the end.

Consider a scenario like this (I forgot the number...): When you move to a certain spot, it will spawn a thing. Then you one shot that thing. So the action card flipped back and the whole monsters bar goes to the end. (1) Your partner wants to spawn one more, but forgets what action the monster is doing, so you need to click the card to check. (2) When your partner spawns the monster, the action card flipped to the front and the bar goes to the front again.

---------------------------------------------------------------------------

2 minor problems that I face, but not necessarily things to change/fix.

12. If the standee numbers and the HP numbers are offset in height a little bit, it will help when you're glancing through monsters. Normal monsters and HP both are white, and sometimes when there are a lot of monsters (Vermling Scouts, or Oozes eh :<), it's a bit hard to read since there are a lot of numbers.

13. I found those monsters with multi-target attacks a bit hard to read (eg: Flaming Bladespinner, Robotic Boltshooter). When there's at least one Normal and one Elite, it reads like:
Attack 3 target 2 / 4 target 3
It definitely takes a while for me parse it, but I'm not sure whether it's worth coloring the elite "target" icon as yellow, or there's a better solution to this. Or maybe it's a just-me problem.

**Comment by Tarmslitaren** [comment]
all good suggestions. 

the rule reminder banners can show either at round start or at round end depending on the rule. I define round start as after you press draw, and round end after press next round. Maybe it is a little bit off, but I can't find a surer way to determine the phase you are in.

**Comment by GarrettChan0** [comment]
> the rule reminder banners can show either at round start or at round end depending on the rule.

It seems usually it's about spawning monsters at the start of the turn, but definitely understand what's the problem you're facing heh.

I added two things, but those can be only-me problems, so we may have some discussion over it.

Still, have to thank you for the constant updates to make it better. I will definitely finish the whole game with X-Haven.

**Comment by GarrettChan0** [comment]
Added a few more after yesterday's session.

I wonder, is there a chance that I can help fixing those capitalization errors directly? It sounds very annoying to you whenever I report those.

**Comment by Tarmslitaren** [comment]
I've already fixed the first reported capitalization errors in version 16.3

All bug reports are valuable and also feature and improvements requests.

I would prefer if you would create new issues rather than pile more on this same one, since it will make it harder and harder to close it ;) Also more text to parse to see what's new. 

Feel free to continue to add typos/capitalization errors in this ticket, but please add others as separate issues.

**Comment by GarrettChan0** [comment]
Oh oops, sorry about this. I think you can close this one and I'll create another thread.

**Comment by Tarmslitaren** [comment]
all fixed except 8, 11, 13 on version 1.7.0. I have taken notes of these and will address later ( except 13, O probably won't do anything for that). closing now
