### ISSUE TITLE
Suggestion- indicators for building 88 (spoilers)

### ISSUE THREAD

**Issue by wealthbeyondmeasure** [Tarmslitaren/FrosthavenAssistant#74]
There doesn't appear to be any way to see which monsters are capturable for the Stables in the app, necessitating getting out their ability cards (which slightly defeats the point). Is there any chance this could this be added to the app, perhaps with a setting toggle?

Apologies if this already exists and I missed it somehow.

**Comment by Tarmslitaren** [comment]
added in version 1.7.0
