### ISSUE TITLE
Manual reordering of figures is undone when a monster is killed

### ISSUE THREAD

**Issue by TylerHelmuth** [Tarmslitaren/FrosthavenAssistant#75]
While playing a scenario the other day we took advantage of the "hold-and drag" feature to reorder some initiatives after initiative had been revealed.  We notice that if a monster was killed during the round that the manually-updated initiative would be reset to the numeric values.

Steps to reproduce:
1. Start a scenario with 2 characters and some spawned monsters
2. Pick initiative numbers and click `draw`.
3. Drag one character to a later initiative than the other.
4. Kill a monster
5. Observe the initiative reverts to the numeric values.

**Comment by Tarmslitaren** [comment]
fixed in 1.6.3 hotfix. Thanks for reporting! Hard to keep track of how all different features interact =)
