### ISSUE TITLE
Set scenario screen broken

### ISSUE THREAD

**Issue by divideandconquer** [Tarmslitaren/FrosthavenAssistant#78]
When I tap set scenario on my galaxy S20 the screen just grays out and I can't do anything.  This is with the February 3rd version of the app

**Comment by Tarmslitaren** [comment]
try clearing your data.

**Comment by divideandconquer** [comment]
That worked. Thanks.

**Comment by IAmMichellis** [comment]
Heads up that my husband (pixel) and I (iPhone) hit the same issue. Clear data worked for him but I couldn’t find a way to clear data, so I uninstall reinstalled.

**Comment by Tarmslitaren** [comment]
I believe this is due to save state getting broken in an earlier version. So it should be a one time issue. If you find that this happens multiple times on the same device in latest version( 1.6.2+), then please notify me.

**Comment by phetrommer** [comment]
Having the same issue on OSX running Ventura 13.1, can't find a way to clear this apps data like on mobile.

**Comment by Tarmslitaren** [comment]
For reference, on windows the data is stored in <user>\AppData\Roaming\com.tarmslitaren\frosthaven_assistant

**Comment by wugmump** [comment]
I am also seeing this issue. It just cripples us. We run on iPhones and a Ventura-running m1. Deleting the container works on the laptop but the only solution on the phones is to delete the app and reinstall.
