### ISSUE TITLE
Curses pull as blesses when both in monster deck

### ISSUE THREAD

**Issue by madjayem** [Tarmslitaren/FrosthavenAssistant#8]
Had 7 curses in the monster deck. Two blesses got added, then more curses. At this point, all curses were being shown as blesses when pulled from the monster deck. Had to remove all curses from the monster deck and re-add them to correct this. 

Edit: attempted to reproduce just on a local game and could not. We were playing a networked game, so that might have something to do with it? Cannot recall who added the last curses, but know that the host added the blesses.

**Comment by Tarmslitaren** [comment]
Thanks for reporting. I've been able to reproduce this issue, somewhat with the following steps:

1. add 7 curses
2. close the app
3. add 2 blesses
4. close the app
5. add 2 curses
6. close app and start again.
7. looked in amd menu, revealed the top 6 cards and noticed more than 2 blesses (there was also one curse. )


So it seems there is an issue with the loading states when it comes to curses and blesses. The same mechanism is used when sending states over network.

**Comment by Tarmslitaren** [comment]
fixed in 1.3.0
