### ISSUE TITLE
Feature Request - Vertical enemy rank and health option

### ISSUE THREAD

**Issue by rcstlouis** [Tarmslitaren/FrosthavenAssistant#82]
## Pleasantries
First I want to say that my friends and I have recently started using the app, and we love it so much! The way it streamlines some of the tedious work of messing with decks and tokens helps keep our table space organized and has largely eliminated the need for asking across the table what a monster's stats are. It makes the game an all-around more pleasant experience. Thank you for making it, and keep up the great work!

## Feature Request 
One thing that my friends and I have noticed while using the app is that the way that the monster rank (e.g. elite # 7) and health number are presented side-by-side can often be visually confusing. The symbols used for them are visually distinct, but we've noticed that when looking back and forth between the battlefield and the app, we need to study it for a second to parse out the numbers all in-line with one another to comprehend which ones are rank and which are health, which can make quick lookups cumbersome.

I'd like to propose the suggestion of an option to present these two numbers vertically (e.g. rank on top, health on bottom) rather than horizontally. In my opinion, this would make the ranks easier to look through to find a monster of interest when planning or resolving a turn. I know that doing this may incur a cost of precious vertical space, but I for one believe that the overall usability would benefit tremendously.

Thank you for your consideration, and thank you again for maintaining such a helpful and fantastic app!

**Comment by Tarmslitaren** [comment]
I will try to do something to make it more clear. blood drop on top like ghh maybe. or change font.

**Comment by rcstlouis** [comment]
That would be fantastic! Looking at Ghh screenshots, the fact that the drop of blood makes the health number a bit smaller than the rank contributes greatly to scanning side-to-side to check the stats for a certain monster with less effort

**Comment by rcstlouis** [comment]
That would be fantastic! Looking at Ghh screenshots, the fact that the drop of blood makes the health number a bit smaller than the rank contributes greatly to scanning side-to-side to check the stats for a certain monster with less effort

**Comment by Tarmslitaren** [comment]
fixed similar to ghh in 1.7.0
