### ISSUE TITLE
Steel Automaton ability card inconsistency 

### ISSUE THREAD

**Issue by GarthonClithith** [Tarmslitaren/FrosthavenAssistant#85]
When using calculations immovable object does not calculate.
Ex.
At lv 1 with normal and elite automatons the ability card Body Block will show

Move 3/3
Shield 3/4
Retaliate 2/2

But Immovable object shows

Shield 4

It should show

Shield 6/7

**Comment by Tarmslitaren** [comment]
fixed along with a couple similar issues in trail of ashes, in version 1.7.0
