### ISSUE TITLE
1.7.0: Missing Frosthaven Scenarios 39-70

### ISSUE THREAD

**Issue by chrisstyves** [Tarmslitaren/FrosthavenAssistant#88]
See title. When attempting to Set Scenario in 1.7.0, it appears that Frosthaven scenarios 39-70 are now missing from the list.

**Comment by GarrettChan0** [comment]
Lol, I was going to report this and it seems we're having the same problem lol

**Comment by Tarmslitaren** [comment]
for the love of...
errant curly brace.

new versions for windows, mac and linux now up. ( made shadow update to same release)
mobile version waiting for review
