### ISSUE TITLE
1.7.0: Ally Deck misaligned

### ISSUE THREAD

**Issue by chrisstyves** [Tarmslitaren/FrosthavenAssistant#89]
In scenarios that use the Ally Deck in 1.7.0, the Ally deck is not aligned vertically with the Monster deck. Normally this is no big deal, but if you have the Loot Deck hidden, the alignment gets worse and the Ally deck goes to the far left side of the screen, and if you draw cards from it, you can't see the animation of the cards drawing. Set Scenario to Frosthaven 1 and turn off the loot deck to reproduce.

**Comment by Tarmslitaren** [comment]
thanks! I'll fix it soon (tm)

**Comment by Tarmslitaren** [comment]
fixed in version 1.7.2
