### ISSUE TITLE
Fish King's stats card has one extra attack on Special 1

### ISSUE THREAD

**Issue by GarrettChan0** [Tarmslitaren/FrosthavenAssistant#90]
1. Fish King's Special 1 shows Attack -1 twice right now.

Funny thing: I actually played it like that and treat him attacking twice in a row :)

------------------------------------

2. In Scenario's 121's final section (123.1), if playing like me, which I don't add my characters, it will make the Automaton in 0HP due to HP being H*(C-1), and in this case, if you added the standee, it will create an invisible thing. Maybe in this case, still make a standee with 0HP or make it H, not sure.

------------------------------------

Extra not related question: I saw there are removing -1/-2 in the monster attack modifier. Are those for challenges? I happen to have that one today.

**Comment by Tarmslitaren** [comment]
I'll check out the fish king error.

the -1/-2 is for a separate hidden frosthaven feature related to appendix f. but if you happen to need to remove -1 or -2 for s challenge that's ok too.

**Comment by GarrettChan0** [comment]
> the -1/-2 is for a separate hidden frosthaven feature related to appendix f. but if you happen to need to remove -1 or -2 for s challenge that's ok too.

Oh OK. I forgot one thing and I put it in already, sorry about that. I was thinking that -1/-2 thing, you may want to implement all the challenges, but I guess that's too much to add for too little.

**Comment by Tarmslitaren** [comment]
I have no plans to add support for everything regarding the challenges. Most will work fine but there's to  my knowledge at least one that's too much work to consider.

**Comment by GarrettChan0** [comment]
> I have no plans to add support for everything regarding the challenges. Most will work fine but there's to my knowledge at least one that's too much work to consider.

That's completely fair. I don't think you should write a lot of exception rules just for a minor aspect of the game which won't be unlocked by all the players either.

**Comment by Tarmslitaren** [comment]
fixed calculations to always assume at least 2 characters.
