### ISSUE TITLE
Turn Order Change with revealed/spawned Enemies

### ISSUE THREAD

**Issue by jonovotny** [Tarmslitaren/FrosthavenAssistant#93]
In the current version, when new enemies get added to the map and draw their action card they always get sorted into the turn order list at their drawn initiative value. However, based on the reveal/spawn rules (Pg. 44 of the rulebook), these new monsters would get to act right after the current actor if their drawn initiative has already passed in that round. Ideally the monster stats and cards should therefore be placed at the expected spot of the turn order, overriding their actions cards initiative.

A more complex case is when a monster type with standees on board has already acted and a new monster of that type is revealed. The newly added monster would get to act right after the current actor. I think the straightforward way to handle this would be to change the original monster entry to the new position below the current actor, change color of the action card back to active (i.e. red), and add highlight the indicator of standees that have to take a turn.

**Comment by Tarmslitaren** [comment]
at least the less complex case id addressed in 1.8.0
