### ISSUE TITLE
Hosting error - or my inexperience 

### ISSUE THREAD

**Issue by grimtoothy** [Tarmslitaren/FrosthavenAssistant#95]
I keep getting a Server error: Null check operator used on a null value.    And The  connect as client and server up address will not permanently access any changes… so any ideas what’s wrong or what I need to do on my end?

**Comment by grimtoothy** [comment]
Ah! I set up a scenario and now when I start the server the error is gone.

**Comment by Tarmslitaren** [comment]
fixed in 1.8.0
