### ISSUE TITLE
Frosthaven Scenario 8 Minor Issue

### ISSUE THREAD

**Issue by kjc17710** [Tarmslitaren/FrosthavenAssistant#98]
Hello! Thanks for making this awesome application!

While playing scenario 8 we noticed there was a button for section book 29.2 to add monsters. This does not appear to line up or be relevant to scenario 8 at all (but also doesn't break anything.) Screenshot for reference.

![image](https://user-images.githubusercontent.com/58891753/219839501-5b294855-0c9f-4246-a439-0a68bdf52543.png)

**Comment by Tarmslitaren** [comment]
fixed in version 1.7.2 ( the section belonged to a different scenario )
