### ISSUE TITLE
Incorrect formula for calculating hazardous terrain damage

### ISSUE THREAD

**Issue by valsinats42** [Tarmslitaren/FrosthavenAssistant#99]
Hello, thanks for the app! Using it for our new GH session, I noticed that the value of the hazardous terrain damage seems incorrect. The current code calculates is as such:

```
static int getHazardValue() {
    return 1 + (_gameState.level.value / 3.0).ceil();
}
```
 But the rulebook (pg. 14) says that

> each hex inflicts half the damage of a trap (rounded down)

So perhaps the code above should be as follows?

```
static int getHazardValue() {
    return (getTrapValue() / 2.0).floor();
}
```

**Comment by Tarmslitaren** [comment]
It is using the Frosthaven formula. 
I will add options to use gloomhaven rules for various things at some point

**Comment by Tarmslitaren** [comment]
added og gloomhaven hazardous terrain calculation as an option in version 1.10.1
